### ISSUE TITLE
Issue with Rajagopal example

### ISSUE THREAD

**Issue by AlleUndKalle** [nimblephysics/nimblephysics#48]
Hi!

Thanks a lot for the amazing work! When I try to run the `rajagopal.py` example, I encountered the error below:

```
❯ python rajagopal.py
Msg [NameManager::issueNewName] (default) The name [Joint_rot_z] is a duplicate, so it has been renamed to [Joint_rot_z(1)]
Msg [NameManager::issueNewName] (default) The name [hip_r_z] is a duplicate, so it has been renamed to [hip_r_z(1)]
Msg [NameManager::issueNewName] (default) The name [hip_l_z] is a duplicate, so it has been renamed to [hip_l_z(1)]
Msg [NameManager::issueNewName] (default) The name [back_z] is a duplicate, so it has been renamed to [back_z(1)]
Msg [NameManager::issueNewName] (default) The name [acromial_r_z] is a duplicate, so it has been renamed to [acromial_r_z(1)]
Msg [NameManager::issueNewName] (default) The name [acromial_l_z] is a duplicate, so it has been renamed to [acromial_l_z(1)]
Traceback (most recent call last):
  File "rajagopal.py", line 12, in <module>
    world.addSkeleton(skel)
TypeError: addSkeleton(): incompatible function arguments. The following argument types are supported:
    1. (self: nimblephysics_libs._nimblephysics.simulation.World, skeleton: nimblephysics_libs._nimblephysics.dynamics.Skeleton) -> str

Invoked with: <nimblephysics_libs._nimblephysics.simulation.World object at 0x7f95df2df880>, <nimblephysics_libs._nimblephysics.biomechanics.OpenSimFile object at 0x7f95df2df8b8>
```
I have the version 0.6.1 installed via pip. How can I solve this problem?

**Comment by keenon** [comment]
Sorry, our API changed and I forgot to update the docs! I've updated them now: https://nimblephysics.org/docs/human-body.html

The change was moving from `nimble.dynamics.Skeleton` to `nimble.biomechanics.OpenSimFile` as the structure returned by our OpenSim parser. That allows us to return other information not normally attached to a skeleton, like where motion capture markers were attached to the skeleton, and (eventually, though we don't support this yet) analytically differentiable muscles.

**Comment by AlleUndKalle** [comment]
Thanks a lot @keenon! I also noticed another issue with the `marker_fit.py` example. I got the below error:

```
Traceback (most recent call last):
  File "marker_fit.py", line 52, in <module>
    result: nimble.biomechanics.MarkerFitResult = fitter.optimize(gold_markers)
AttributeError: 'nimblephysics_libs._nimblephysics.biomechanics.Mar' object has no attribute 'optimize'
```

**Comment by keenon** [comment]
Ah, you've stumbled on research code that shouldn't be in `new_examples`. The `marker_fit.py` was an early version of the code at `new_examples/marker_fit/marker_fit_api.py`, and the API is out of date. I've deleted `marker_fit.py`, and moved the `new_examples/marker_fit/*` folder to `research/marker_fit/*` in the `python` directory.

You can run `research/marker_fit/marker_fit_api.py` if you're curious about in-progress work, but the project isn't finished yet and hasn't been published, so is undocumented and could break at any time. Proceed with caution, things may explode :boom:
