### ISSUE TITLE
Joint degree of freedom

### ISSUE THREAD

**Issue by zhangy76** [nimblephysics/nimblephysics#79]
Hi,

The object is described via generalized coordinate. I wonder how to get the joint DOF of each link? The question may be very basic... So I wonder if there is any documents besides the examples in the current repository that introduce the basic functions?

Thanks

**Comment by gonultasbu** [comment]
Hello,

You can do something like this:

```
for joint in agent.getJoints():
    print(joint.getName())
```

instead of `getName() `function you can use the `getNumDofs()`. Also, you can use VS Code's interactive debugger to inspect member functions to find the functions you may need in the future.

All the best.

**Comment by zhangy76** [comment]
They work well! Thank you!

Best,
Yufei
