### ISSUE TITLE
How to reset the joint DOF

### ISSUE THREAD

**Issue by zhangy76** [nimblephysics/nimblephysics#80]
Hi,

I am loading a humanoid from a urdf file. It seems that we can not directly define a ball joint in urdf. So I wonder if we can load a urdf with 1 DOF and then change the DOF to 3 after loading the model into the nimble? 

Thanks

**Comment by gonultasbu** [comment]
I have tried doing that and have not been successful at directly modifying joints, however if you load an .SDF file which supports ball joints, you can add ball joints to your simulation environment.

**Comment by zhangy76** [comment]
Thanks for the reply. Currently I follow what you said and avoid the problem by modifying an .skel file.
