### ISSUE TITLE
Bullet and multi_sphere collision detector

### ISSUE THREAD

**Issue by zhangy76** [nimblephysics/nimblephysics#81]
Hi,

I am trying to load a .skel file defined by a collision detector of "bullet" and a body link of multi_sphere. The skeleton can be loaded but I the following error message pop up 

> Warning [Factory-impl.hpp:168] [Factory] Failed to create an object of 'N4dart9collision17CollisionDetectorE' class with the key (type: 'Ss'). Returning nullptr instead.
Warning [SkelParser.cpp:726] Unknown collision detector[bullet]. Default collision detector[dart] will be loaded.
Error [DARTCollisionDetector.cpp:304] [DARTCollisionDetector] Attempting to create shape type [MultiSphereConvexHullShape] that is not supported by DARTCollisionDetector. Currently, only BoxShape and EllipsoidShape (only when all the radii are equal) and SphereShape and MeshShape and CapsuleShape are supported. This shape will always get penetrated by other objects.
Error [DARTCollisionDetector.cpp:304] [DARTCollisionDetector] Attempting to create shape type [MultiSphereConvexHullShape] that is not supported by DARTCollisionDetector. Currently, only BoxShape and EllipsoidShape (only when all the radii are equal) and SphereShape and MeshShape and CapsuleShape are supported. This shape will always get penetrated by other objects.
> 

Is this a bug or we can not define the .skel file like that?

**Comment by amdee** [comment]
Hi @zhangy76, How did you resolve this? I am getting the same error while trying to load different urdf

**Comment by zhangy76** [comment]
Sorry I do know the solution.
